apiVersion: v1
kind: Service
metadata:
  name: svc-webapp
  labels:
    app: svc-label
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: pod-webapp-dev

